---
title: "toolik_chem"
author: "zachyloo"
format: html
editor: visual
---

# Biochemistry Analysis at Toolik Lake, Alaska

```{r}
# load packages
library(janitor)
library(tidyverse)
library(here)
```

```{r}
# load data, adjust default "." to "NA"
toolik_biochem <- read_csv(here::here("data", "2011_Kling_Akchem.csv"), na = c(".", "NA"))　|> janitor::clean_names()
```

```{r}
# filter rows using filter
inlet_biochem <- dplyr::filter(toolik_biochem, site == "Toolik Inlet")
# select cols using dplyr::select()
inlet_biochem <- inlet_biochem |> select(p_h, doc_u_m, tdn_u_m)
```

```{r}
# mean value of each col: for loop
# df[[i]] calls the ith col!

# storage vector
inlet_biochem_fl <- vector(mode = "numeric", length = ncol(inlet_biochem))

for (col in 1:ncol(inlet_biochem)) {
  mean_value <- mean(inlet_biochem[[col]], na.rm = TRUE)
  inlet_biochem_fl[[col]] <- mean_value
}
print(inlet_biochem_fl)

# mean value of each col: apply()
inlet_biochem_apply <- vector(mode = "numeric", length = ncol(inlet_biochem)) # storage vector !

inlet_biochem_apply <- apply(X = inlet_biochem, MARGIN = 2, FUN = mean, na.rm = TRUE) 
print(inlet_biochem_apply)

# mean value of each col: {purrr}
inlet_biochem_pur <- purrr::map_dbl(.x = inlet_biochem, .f = mean, na.rm = TRUE)
print(inlet_biochem_pur)

# mean value of each col: dplyr::
library(tidyverse)
inlet_biochem_dp <- inlet_biochem |> 
  summarize(across(where(is.numeric), mean, na.rm = TRUE))
inlet_biochem_dp
```

